using BookFlix.Core.Repositories;
using BookFlix.Core.Service_Interfaces;
using BookFlix.Core.Services.Validation;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace BookFlix.Core.Services
{
    public class LocalFileService : IFileService
    {
        private readonly IBookRepository _bookRepository;
        private string _bookDirectory;
        private readonly ILogger<LocalFileService> _logger;

        public LocalFileService(IBookRepository bookRepository, IConfiguration configuration, ILogger<LocalFileService> logger)
        {
            _bookRepository = bookRepository;
            SetBookDirectory();
            _logger = logger;
        }

        public async Task<Result<string>> UploadFileAsync(Guid bookID, IFormFile file)
        {
            var result= ValidateFile(file);
            if (result.IsFailure) return Result.Failure<string>(result.Error);

            var book = await _bookRepository.GetByIDAsync(bookID);
            if (book is null)
            {
                _logger.LogError($"Book with ID {bookID} not found.");
                return Result.Failure<string>(Error.NotFound("BookNotFound"));
            }

            string filePath = null;
            using var transaction = await _bookRepository.BeginTransactionAsync();
            try
            {
                filePath = book.FileLocation != null ? Path.Combine(_bookDirectory, book.FileLocation) : null;

                result = DeleteBookFile(filePath);
                if (result.IsFailure) return Result.Failure<string>(result.Error);
               
                filePath = SetAutoGeneratedFileName();
                await SaveFileToDirectory(file, filePath);

                var fileNameAsFileLocation = Path.GetFileName(filePath);
                await _bookRepository.UpdateFileLocationAsync(bookID, fileNameAsFileLocation);
                await transaction.CommitAsync();

                return Result.Success(fileNameAsFileLocation);
            }
            catch (IOException ex)
            {
                await transaction.RollbackAsync();

                result = DeleteBookFile(filePath);

                _logger.LogError(ex, "IO error uploading file for book ID {BookID}", bookID);
                return Result.Failure<string>(Error.Failure("FileSaveStorageError"));
            }
            catch (Exception ex)
            {
                await transaction.RollbackAsync();
                _logger.LogError(ex, "Unexpected error uploading file for book ID {BookID}", bookID);
                return Result.Failure<string>(Error.Failure("FileUnexpectedUploadError"));
            }
        }

        private Result DeleteBookFile(string fileLocation)
        {
            if (!string.IsNullOrEmpty(fileLocation))
            {
                var fullFileLocation = Path.Combine(_bookDirectory, Path.GetFileName(fileLocation));
                if (File.Exists(fullFileLocation))
                {
                    try
                    {
                        File.Delete(fullFileLocation);
                    }
                    catch (IOException ex)
                    {
                        _logger.LogError(ex, $"IO error deleting file: {fileLocation}");
                        return Result.Failure(Error.Failure("FileDeletionFailed"));
                    }
                }
            }
            return Result.Success();
        }

        private void SetBookDirectory()
        {
            string folderPath = Path.Combine(Directory.GetCurrentDirectory(), "BookStorage");

            if (!Directory.Exists(folderPath)) Directory.CreateDirectory(folderPath);

            _bookDirectory = folderPath;
        }

        private Result ValidateFile(IFormFile file)
        {
            if (file == null || file.Length == 0)
            {
                _logger.LogError("File is null or empty.");
                return Result.Failure(Error.Failure("FileNullOrEmpty"));
            }

            if (file.ContentType != "application/pdf")
            {
                _logger.LogError("Only PDF files are allowed.");
                return Result.Failure(Error.Failure("InvalidFileType"));
            }

            if (file.Length > 100 * 1024 * 1024)
            {
                _logger.LogError("File size exceeds 100MB limit.");
                return Result.Failure(Error.Failure("FileSizeExceed100MB"));
            }

            return Result.Success();
        }

        private async Task SaveFileToDirectory(IFormFile file, string filePath)
        {
            var directory = Path.GetDirectoryName(filePath) ?? throw new InvalidOperationException("Invalid file path.");
            if (!Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            using var stream = new FileStream(filePath, FileMode.Create);
            await file.CopyToAsync(stream);
        }

        private string SetAutoGeneratedFileName()
        {
            string fileName = $"{Guid.NewGuid()}.pdf";
            return Path.Combine(_bookDirectory, fileName);
        }
    }
}